:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - default
  - mailers
:schedule:
  availabilities_update_job:
    cron: '00 12 * * *'
    class: AvailabilitiesUpdateJob