:concurrency: 5
staging:
  :concurrency: 10
production:
  :concurrency: 10
:queues:
  - default
  - mailers
  # :schedule:
  # hello_world:
  #   cron: ''   # Runs once per minute
  #   class: HelloWorld